# Generated by Django 5.2.7 on 2025-11-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='descripcion',
            new_name='description',
        ),
    ]
