# Generated by Django 5.2.7 on 2025-11-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_descripcion_stores_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
