# Generated by Django 5.2.7 on 2025-12-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_products_delete_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='stores',
            new_name='Store',
        ),
    ]
